server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:sockDB;MODE=PostgreSQL
    username: root
    password:
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false



jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMzgyNTA1NCwiaWF0IjoxNjMzODI1MDU0fQ.QMZSvfg10eYIF5rbPbezNCtgOn814AaYQUFpHPFrz1Q

